apiVersion: 1                   # config file version

deleteDatasources:              # list of datasources that should be deleted from the database
  - name: Prometheus
    orgId: 1

datasources:                    # list of datasources to insert/update depending
  - name: Prometheus            # <string, required> name of the datasource. Required
    type: prometheus            # <string, required> datasource type. Required
    access: proxy               # <string, required> access mode. direct or proxy. Required
    orgId: 1                    # <int> org id. will default to orgId 1 if not specified
    url: http://prometheus:9090 # <string> url
    password:                   # <string> database password, if used
    user:                       # <string> database user, if used
    database:                   # <string> database name, if used
    basicAuth: false            # <bool> enable/disable basic auth
    basicAuthUser:              # <string> basic auth username, if used
    basicAuthPassword:          # <string> basic auth password, if used
    withCredentials:            # <bool> enable/disable with credentials headers
    isDefault: true             # <bool> mark as default datasource. Max one per org
    jsonData:                   # <map> fields that will be converted to json and stored in json_data
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    secureJsonData:             # <string> json object of data that will be encrypted.
      tlsCACert: "..."
      tlsClientCert: "..."
      tlsClientKey: "..."
    version: 1
    editable: true              # <bool> allow users to edit datasources from the UI.